[project]
name = "markitdown-wrap-mcp"
version = "0.1.0"
description = "MCP server for Markitdown conversion service"
authors = [
    {name = "Your Name", email = "your.email@example.com"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "markitdown[all]",
    "mcp[cli]",
]
